### ISSUE TITLE
Cannot compile sketch for ESP8266

### ISSUE THREAD

**Issue by topsurgeon** [hello-robot/stretch_factory#20]
I cannot compile sketch for ESP8266

I am ble to compile sketches for arduino uno but cant for the 8266

MacOs El Capitaln 10.11.6 Arduino 1.8.14
Board manager installed https://arduino.esp8266.com/stable/package_esp8266com_index.json
Python 3 installed

Error message on attempting to compile a sketch is :

dyld: lazy symbol binding failed: Symbol not found: _getentropy
  Referenced from: /Users/petersmacbookpro/Library/Arduino15/packages/esp8266/tools/python3/3.7.2-post1/python3
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _getentropy
  Referenced from: /Users/petersmacbookpro/Library/Arduino15/packages/esp8266/tools/python3/3.7.2-post1/python3
  Expected in: /usr/lib/libSystem.B.dylib

signal: trace/BPT trap
/Applications/Arduino.app/Contents/Java/arduino-builder returned 255
Error compiling for board Generic ESP8266 Module.

Please help

**Comment by hello-binit** [comment]
Hi @topsurgeon, apologies for the late reply. If you're still facing this issue, please open another issue and provide more details on which sketch you're attempting to compile.
