### ISSUE TITLE
Firmware updater tool fails when Stretch Firmware is not in Arduino user directory

### ISSUE THREAD

**Issue by hello-binit** [hello-robot/stretch_factory#9]
Using the `RE1_firmware_updater.py` tool fails when the [stretch_firmware](https://github.com/hello-robot/stretch_firmware) repo isn't cloned into the arduino user directory, as defined in the `~/.arduino15/arduino-cli.yaml` config file.

In my case, my config file has:
```
directories:
  user: /home/hello-binit/repos/stretch_firmware/arduino
```

Since the `RE1_firmware_updater.py` tool clones stretch_firmware, it can also also use the `--config-file` [flag on arduino-cli](https://arduino.github.io/arduino-cli/latest/commands/arduino-cli_compile/#options-inherited-from-parent-commands) to set the user directory to the `/tmp` folder where the repo is cloned.

**Comment by aedsinger** [comment]
Resolved with PR https://github.com/hello-robot/stretch_factory/pull/12
